/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPodsRouteImport } from './routes/_authenticated/pods'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedGpsRouteImport } from './routes/_authenticated/gps'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCostsRouteImport } from './routes/_authenticated/costs'
import { Route as AuthenticatedContainersRouteImport } from './routes/_authenticated/containers'
import { Route as AuthenticatedClaimsRouteImport } from './routes/_authenticated/claims'
import { Route as AuthenticatedBordersRouteImport } from './routes/_authenticated/borders'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPodsRoute = AuthenticatedPodsRouteImport.update({
  id: '/pods',
  path: '/pods',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGpsRoute = AuthenticatedGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCostsRoute = AuthenticatedCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContainersRoute = AuthenticatedContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClaimsRoute = AuthenticatedClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBordersRoute = AuthenticatedBordersRouteImport.update({
  id: '/borders',
  path: '/borders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/borders': typeof AuthenticatedBordersRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/containers': typeof AuthenticatedContainersRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/gps': typeof AuthenticatedGpsRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/pods': typeof AuthenticatedPodsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/tracking': typeof AuthenticatedTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/borders': typeof AuthenticatedBordersRoute
  '/claims': typeof AuthenticatedClaimsRoute
  '/containers': typeof AuthenticatedContainersRoute
  '/costs': typeof AuthenticatedCostsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/gps': typeof AuthenticatedGpsRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/pods': typeof AuthenticatedPodsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/tracking': typeof AuthenticatedTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/borders': typeof AuthenticatedBordersRoute
  '/_authenticated/claims': typeof AuthenticatedClaimsRoute
  '/_authenticated/containers': typeof AuthenticatedContainersRoute
  '/_authenticated/costs': typeof AuthenticatedCostsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/gps': typeof AuthenticatedGpsRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/pods': typeof AuthenticatedPodsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/borders'
    | '/claims'
    | '/containers'
    | '/costs'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/gps'
    | '/incidents'
    | '/pods'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/analytics'
    | '/borders'
    | '/claims'
    | '/containers'
    | '/costs'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/drivers'
    | '/fleet'
    | '/gps'
    | '/incidents'
    | '/pods'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/borders'
    | '/_authenticated/claims'
    | '/_authenticated/containers'
    | '/_authenticated/costs'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/drivers'
    | '/_authenticated/fleet'
    | '/_authenticated/gps'
    | '/_authenticated/incidents'
    | '/_authenticated/pods'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/shipments'
    | '/_authenticated/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pods': {
      id: '/_authenticated/pods'
      path: '/pods'
      fullPath: '/pods'
      preLoaderRoute: typeof AuthenticatedPodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gps': {
      id: '/_authenticated/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof AuthenticatedGpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/costs': {
      id: '/_authenticated/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthenticatedCostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/containers': {
      id: '/_authenticated/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AuthenticatedContainersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/claims': {
      id: '/_authenticated/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof AuthenticatedClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borders': {
      id: '/_authenticated/borders'
      path: '/borders'
      fullPath: '/borders'
      preLoaderRoute: typeof AuthenticatedBordersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBordersRoute: typeof AuthenticatedBordersRoute
  AuthenticatedClaimsRoute: typeof AuthenticatedClaimsRoute
  AuthenticatedContainersRoute: typeof AuthenticatedContainersRoute
  AuthenticatedCostsRoute: typeof AuthenticatedCostsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedGpsRoute: typeof AuthenticatedGpsRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedPodsRoute: typeof AuthenticatedPodsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBordersRoute: AuthenticatedBordersRoute,
  AuthenticatedClaimsRoute: AuthenticatedClaimsRoute,
  AuthenticatedContainersRoute: AuthenticatedContainersRoute,
  AuthenticatedCostsRoute: AuthenticatedCostsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedGpsRoute: AuthenticatedGpsRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedPodsRoute: AuthenticatedPodsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
